{
 "title": "Main Dashboard",
 "description": "Main Dashboard",
 "tags": [
  "main",
  "vm",
  "host",
  "pihole",
  "internet"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_proxmox\"} - node_boot_time_seconds{job=\"node_exporter_proxmox\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_proxmox\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_proxmox\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_proxmox\"}) by (cpu))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_media\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_media\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_media\"}) by (cpu))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_system\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_system\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_system\"}) by (cpu))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_network\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_network\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_network\"}) by (cpu))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_public\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_public\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_public\"}) by (cpu))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_apps\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_apps\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_apps\"}) by (cpu))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_nas\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_nas\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_nas\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "alertlist", "gridPos": { "h": 10, "w": 4, "x": 20, "y": 1 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_proxmox\"}) by (cpu))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(node_memory_MemTotal_bytes{job=\"node_exporter_proxmox\"})+500000000"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node_exporter_proxmox\",mountpoint=\"/\"}+12111111111",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node_exporter_proxmox\",mountpoint=\"/mnt/storage01\"}+28111000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node_exporter_proxmox\",device=\"nvme0n1\"} [$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node_exporter_proxmox\",device=\"sda\"} [$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average system load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node_exporter_proxmox\"}) /  count(count(node_cpu_seconds_total{job=\"node_exporter_proxmox\"}) by (cpu)) * 100",
     "legendFormat": "1m"
    },
    {
     "expr": "avg(node_load5{job=\"node_exporter_proxmox\"}) /  count(count(node_cpu_seconds_total{job=\"node_exporter_proxmox\"}) by (cpu)) * 100",
     "legendFormat": "5m"
    },
    {
     "expr": "avg(node_load15{job=\"node_exporter_proxmox\"}) /  count(count(node_cpu_seconds_total{job=\"node_exporter_proxmox\"}) by (cpu)) * 100",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Hardware temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_proxmox\", chip=\"platform_coretemp_0\",sensor=\"temp1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_proxmox\", chip=\"nvme_nvme0\",sensor=\"temp1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smartprom_airflow_temperature_cel_raw",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_proxmox\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_proxmox\"} - node_memory_MemFree_bytes{job=\"node_exporter_proxmox\"} - (node_memory_Cached_bytes{job=\"node_exporter_proxmox\"} + node_memory_Buffers_bytes{job=\"node_exporter_proxmox\"} + node_memory_SReclaimable_bytes{job=\"node_exporter_proxmox\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node_exporter_proxmox\"} + node_memory_Buffers_bytes{job=\"node_exporter_proxmox\"} + node_memory_SReclaimable_bytes{job=\"node_exporter_proxmox\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"node_exporter_proxmox\"} - node_memory_SwapFree_bytes{job=\"node_exporter_proxmox\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_proxmox\", chip=\"platform_coretemp_0\",sensor=\"temp1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_hwmon_temp_celsius{job=\"node_exporter_proxmox\", chip=\"nvme_nvme0\",sensor=\"temp1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "smartprom_airflow_temperature_cel_raw",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_proxmox\",device!~'rootfs',mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_proxmox\",device!~'rootfs',mountpoint=\"/\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device=\"//192.168.0.110/shows\"} * 100) / node_filesystem_size_bytes{device=\"//192.168.0.110/shows\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device=\"//192.168.0.110/movies\"} * 100) / node_filesystem_size_bytes{device=\"//192.168.0.110/movies\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "power", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((power * $__interval_ms / 3600000)  / 1000000) * 105.88",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "power", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "⏬⏫ Internet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_downloaded_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_session_downloaded_bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_download_speed_bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(qbittorrent_torrent_seeders)"
    },
    {
     "expr": "sum(qbittorrent_torrent_leechers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbittorrent_global_torrents", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_torrent_progress < 1.0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_alltime_uploaded_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_session_uploaded_bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "qbittorrent_global_upload_speed_bytes"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qbittorrent_global_ratio  " }
   ]
  },
  {
   "title": "Cumulative Download/Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "qbittorrent_torrent_download_speed_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Upload Speed by Torrent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "qbittorrent_torrent_upload_speed_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "🍓PI-Hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_status", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_dns_queries_all_types", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_blocked_today" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_unique_clients" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_dns_queries_all_types", "legendFormat": "{{ job }}" },
    { "expr": "pihole_ads_blocked_today", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "🖥️ Virtual Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_media\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_media\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_media\"}) by (cpu))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_media\"} - node_memory_MemFree_bytes{job=\"node_exporter_media\"} - (node_memory_Cached_bytes{job=\"node_exporter_media\"} + node_memory_Buffers_bytes{job=\"node_exporter_media\"} + node_memory_SReclaimable_bytes{job=\"node_exporter_media\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_media\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_media\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_media\"} - node_boot_time_seconds{job=\"node_exporter_media\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_media\"}) by (cpu))"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_media\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",job=\"node_exporter_media\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_system\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_system\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_system\"}) by (cpu))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_system\"} - node_memory_MemFree_bytes{job=\"node_exporter_system\"} - (node_memory_Cached_bytes{job=\"node_exporter_system\"} + node_memory_Buffers_bytes{job=\"node_exporter_system\"} + node_memory_SReclaimable_bytes{job=\"node_exporter_system\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_system\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_system\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_system\"} - node_boot_time_seconds{job=\"node_exporter_system\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_system\"}) by (cpu))"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_system\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",job=\"node_exporter_system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_apps\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_apps\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_apps\"}) by (cpu))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_apps\"} - node_memory_MemFree_bytes{job=\"node_exporter_apps\"} - (node_memory_Cached_bytes{job=\"node_exporter_apps\"} + node_memory_Buffers_bytes{job=\"node_exporter_apps\"} + node_memory_SReclaimable_bytes{job=\"node_exporter_apps\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_apps\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_apps\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_apps\"} - node_boot_time_seconds{job=\"node_exporter_apps\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_apps\"}) by (cpu))"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_apps\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",job=\"node_exporter_apps\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_network\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_network\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_network\"}) by (cpu))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_network\"} - node_memory_MemFree_bytes{job=\"node_exporter_network\"} - (node_memory_Cached_bytes{job=\"node_exporter_network\"} + node_memory_Buffers_bytes{job=\"node_exporter_network\"} + node_memory_SReclaimable_bytes{job=\"node_exporter_network\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_network\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_network\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_network\"} - node_boot_time_seconds{job=\"node_exporter_network\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_network\"}) by (cpu))"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_network\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",job=\"node_exporter_network\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_public\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_public\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_public\"}) by (cpu))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_public\"} - node_memory_MemFree_bytes{job=\"node_exporter_public\"} - (node_memory_Cached_bytes{job=\"node_exporter_public\"} + node_memory_Buffers_bytes{job=\"node_exporter_public\"} + node_memory_SReclaimable_bytes{job=\"node_exporter_public\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_public\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_public\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_public\"} - node_boot_time_seconds{job=\"node_exporter_public\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_public\"}) by (cpu))"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_public\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",job=\"node_exporter_public\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"node_exporter_nas\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"node_exporter_nas\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"node_exporter_nas\"}) by (cpu))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_nas\"} - node_memory_MemFree_bytes{job=\"node_exporter_nas\"} - (node_memory_Cached_bytes{job=\"node_exporter_nas\"} + node_memory_Buffers_bytes{job=\"node_exporter_nas\"} + node_memory_SReclaimable_bytes{job=\"node_exporter_nas\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"node_exporter_nas\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"node_exporter_nas\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node_exporter_nas\"} - node_boot_time_seconds{job=\"node_exporter_nas\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node_exporter_nas\"}) by (cpu))"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter_nas\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",job=\"node_exporter_nas\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}